language: python
python:
  - '3.7.4'
before_install:
  - mysql -e 'CREATE DATABASE enwp10_test; CREATE DATABASE enwikip_test;'
install:
  - pip install -r requirements.txt
  - pip install codecov pytest pytest-cov
script:
  - nosetests --with-coverage
after_success:
  - codecov
services:
  - mysql
  - redis-server
