version: '3.5'
services:

  workers:
    image: openzim/wp1bot-workers
    container_name: wp1bot-workers
    volumes:
      - /data/wp1bot/credentials.py:/usr/src/app/wp1/credentials.py
    links:
      - redis
    restart: always
    depends_on:
      - redis

  web:
    image: wp1bot-web
    container_name: wp1bot-web
    ports:
      - 9181:9181
    volumes:
      - /data/wp1bot/rq-credentials.txt:/usr/src/app/rq-credentials.txt
    links:
      - redis
    restart: always
    depends_on:
      - redis

  redis:
    image: redis
    container_name: wp1bot-redis
    expose:
      - 6379
    restart: always
